[package]
name = "grex-packet-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casperfpga = "0.1.0"
num-complex = "0.4.3"
socket2 = "0.5.2"
